---
- name: Install dependencies
  hosts: all
  debugger: on_failed
  tasks:
    - name: Update and upgrade apt packages
      become: yes
      apt:
        upgrade: yes
        update_cache: yes

    - name: Install git
      become: yes
      apt:
        name: git

    - name: Install python3.8
      become: yes
      apt:
        name: python3.8

    - name: install pip3
      become: yes
      apt:
        name: python3-pip
    
    - name: Install numpy python package
      pip:
        name: numpy

    - name: Install absl python package
      pip:
        name: absl-py

    - name: Install torch python package
      pip:
        name: torch

    - name: Install torchvision python package
      pip:
        name: torchvision  
